/**
 * VocalProfile component: Displays the Vocal profile generated by AI analysis.
 * Shows 5 dimensions in the form of a card grid: pitch, rhythm, mood, timbre, expression.
 * Each dimension contains numerical indicators and natural language descriptions.
 * Responsive layout: 1 column for mobile, 2 columns for tablet, and 4 columns for desktop.
 */

import type { VocalProfile as VocalProfileType } from '../../types'

interface VocalProfileProps {
  /** Vocal profile data */
  profile: VocalProfileType
}

/**
 * Meter bar component: visually displays values in the 0-1 range.
 *
 * @param value - a number between 0 and 1
 * @param label - Metric label
 * @param color - Meter bar color, defaults to primary
 */
function MeterBar({
  value,
  label,
  color = 'var(--color-primary)',
}: {
  value: number
  label: string
  color?: string
}) {
  const percentage = Math.round(value * 100)
  return (
    <div style={{ marginBottom: 'var(--space-2)' }}>
      <div
        style={{
          display: 'flex',
          justifyContent: 'space-between',
          fontSize: 'var(--font-size-xs)',
          color: 'var(--color-text-secondary)',
          marginBottom: 2,
        }}
      >
        <span>{label}</span>
        <span>{percentage}%</span>
      </div>
      <div
        style={{
          height: 6,
          backgroundColor: 'var(--color-surface-dark)',
          borderRadius: 'var(--radius-full)',
          overflow: 'hidden',
        }}
        role="progressbar"
        aria-valuenow={percentage}
        aria-valuemin={0}
        aria-valuemax={100}
        aria-label={`${label}: ${percentage}%`}
      >
        <div
          style={{
            width: `${percentage}%`,
            height: '100%',
            backgroundColor: color,
            borderRadius: 'var(--radius-full)',
            transition: 'width 0.5s ease',
          }}
        />
      </div>
    </div>
  )
}

/**
 * Trait card component: displays a single dimension of the vocal profile.
 */
function TraitCard({
  title,
  description,
  children,
}: {
  title: string
  description: string
  children: React.ReactNode
}) {
  return (
    <div
      style={{
        backgroundColor: 'white',
        borderRadius: 'var(--radius-lg)',
        padding: 'var(--space-5)',
        boxShadow: 'var(--shadow-sm)',
        border: '1px solid var(--color-border)',
      }}
    >
      <h3
        style={{
          fontSize: 'var(--font-size-base)',
          fontWeight: 'var(--font-weight-semibold)',
          marginBottom: 'var(--space-3)',
          color: 'var(--color-text)',
        }}
      >
        {title}
      </h3>
      <div style={{ marginBottom: 'var(--space-3)' }}>{children}</div>
      <p
        style={{
          fontSize: 'var(--font-size-sm)',
          color: 'var(--color-text-secondary)',
          lineHeight: 1.5,
        }}
      >
        {description}
      </p>
    </div>
  )
}

export default function VocalProfile({ profile }: VocalProfileProps) {
  return (
    <div>
      {/* Confidence indicator */}
      <div
        style={{
          display: 'flex',
          alignItems: 'center',
          gap: 'var(--space-2)',
          marginBottom: 'var(--space-5)',
          fontSize: 'var(--font-size-sm)',
          color: 'var(--color-text-secondary)',
        }}
      >
        <span>Analysis Confidence:</span>
        <span
          style={{
            fontWeight: 'var(--font-weight-semibold)',
            color:
              profile.confidence > 0.7
                ? 'var(--color-confidence-high)'
                : profile.confidence > 0.4
                  ? 'var(--color-confidence-medium)'
                  : 'var(--color-text-secondary)',
          }}
        >
          {Math.round(profile.confidence * 100)}%
        </span>
      </div>

      {/* Trait card grid */}
      <div
        style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))',
          gap: 'var(--space-4)',
        }}
      >
        {/* Pitch dimension */}
        <TraitCard title="Pitch Range" description={profile.pitch.description}>
          <div
            style={{
              fontSize: 'var(--font-size-xl)',
              fontWeight: 'var(--font-weight-bold)',
              color: 'var(--color-primary)',
              marginBottom: 'var(--space-2)',
            }}
          >
            {profile.pitch.range_low} – {profile.pitch.range_high}
          </div>
          <div
            style={{
              fontSize: 'var(--font-size-xs)',
              color: 'var(--color-text-secondary)',
              marginBottom: 'var(--space-2)',
            }}
          >
            Comfortable zone: {profile.pitch.comfortable_zone}
          </div>
          <MeterBar value={profile.pitch.stability} label="Pitch Stability" />
        </TraitCard>

        {/* Rhythm dimension */}
        <TraitCard title="Rhythm" description={profile.rhythm.description}>
          {profile.rhythm.tempo_bpm && (
            <div
              style={{
                fontSize: 'var(--font-size-xl)',
                fontWeight: 'var(--font-weight-bold)',
                color: 'var(--color-primary)',
                marginBottom: 'var(--space-2)',
              }}
            >
              ~{Math.round(profile.rhythm.tempo_bpm)} BPM
            </div>
          )}
          <MeterBar value={profile.rhythm.regularity} label="Rhythm Regularity" />
        </TraitCard>

        {/* Mood dimension */}
        <TraitCard title={`Mood: ${profile.mood.label}`} description={profile.mood.description}>
          <MeterBar value={profile.mood.valence} label="Positivity" color="#10B981" />
          <MeterBar value={profile.mood.energy} label="Energy" color="#F59E0B" />
          <MeterBar value={profile.mood.tension} label="Tension" color="#EF4444" />
        </TraitCard>

        {/* Timbre dimension */}
        <TraitCard
          title={`Timbre: ${profile.timbre.label}`}
          description={profile.timbre.description}
        >
          <MeterBar value={profile.timbre.warmth} label="Warmth" color="#F97316" />
          <MeterBar value={profile.timbre.brightness} label="Brightness" color="#3B82F6" />
          <MeterBar value={profile.timbre.breathiness} label="Breathiness" color="#8B5CF6" />
        </TraitCard>

        {/* Expression dimension */}
        <TraitCard title="Expression" description={profile.expression.description}>
          <MeterBar value={profile.expression.vibrato} label="Vibrato" />
          <MeterBar value={profile.expression.dynamic_range} label="Dynamic Range" />
          <div
            style={{
              fontSize: 'var(--font-size-xs)',
              color: 'var(--color-text-secondary)',
              marginTop: 'var(--space-1)',
            }}
          >
            Articulation: {profile.expression.articulation}
          </div>
        </TraitCard>
      </div>
    </div>
  )
}
